### ISSUE TITLE
Kompatibelität auf 8.x

### ISSUE THREAD

**Issue by Loppla** [Rhein-Main-Kreis/ct-cal#2]
Leider wirft es bei php 8.0 einen Fehler.

**Comment by MurusM** [comment]
Ja, ich habe heute auch auf 8.4 geupdatet, seitem funktioniert das Plugin leider auch nicht mehr. Hier die Fehlermeldung:

Fehler-Details
==============
Ein Fehler vom Typ E_ERROR wurde in der Zeile 213 der Datei /usr/www/users/lkgwsc/lkg-jan-2023/wp-content/plugins/ct-cal/shortcode.php verursacht. Fehlermeldung: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, stdClass given in /usr/www/users/lkgwsc/lkg-jan-2023/wp-content/plugins/ct-cal/shortcode.php:213
Stack trace:
#0 /usr/www/users/lkgwsc/lkg-jan-2023/wp-content/plugins/ct-cal/shortcode.php(22): CalendarShortcode->getHtmlCalendarEvents()
#1 /usr/www/users/lkgwsc/lkg-jan-2023/wp-includes/shortcodes.php(434): CalendarShortcode->churchtool_shortcode()
#2 [internal function]: do_shortcode_tag()
#3 /usr/www/users/lkgwsc/lkg-jan-2023/wp-includes/shortcodes.php(273): preg_replace_callback()
#4 /usr/www/users/lkgwsc/lkg-jan-2023/wp-includes/class-wp-hook.php(324): do_shortcode()
#5 /usr/www/users/lkgwsc/lkg-jan-2023/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#6 /usr/www/users/lkgwsc/lkg-jan-2023/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php(1961): apply_filters()
#7 /usr/www/users/lkgwsc/lkg-jan-2023/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php(655): WP_REST_Posts_Controller->prepare_item_for_response()
#8 /usr/www/users/lkgwsc/lkg-jan-2023/wp-includes/rest-api/class-wp-rest-server.php(1292): WP_REST_Posts_Controller->get_item()
#9 /usr/www/users/lkgwsc/lkg-jan-2023/wp-includes/rest-api/class-wp-rest-server.php(1125): WP_REST_Server->respond_to_request()
#10 /usr/www/users/lkgwsc/lkg-jan-2023/wp-includes/rest-api.php(586): WP_REST_Server->dispatch()
#11 /usr/www/users/lkgwsc/lkg-jan-2023/wp-includes/rest-api.php(2973): rest_do_request()
#12 [internal function]: rest_preload_api_request()
#13 /usr/www/users/lkgwsc/lkg-jan-2023/wp-includes/block-editor.php(754): array_reduce()
#14 /usr/www/users/lkgwsc/lkg-jan-2023/wp-admin/edit-form-blocks.php(114): block_editor_rest_api_preload()
#15 /usr/www/users/lkgwsc/lkg-jan-2023/wp-admin/post.php(187): require('/usr/www/users/...')
#16 {main}
 thrown
